# Generated by Django 4.2.21 on 2025-05-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebestibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoBebestible', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('mesa', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PlatoDeFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('agregados', models.CharField(max_length=45)),
                ('tipoProducto', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('cantidadPersonas', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidosMesero',
            fields=[
                ('idPedidosMesero', models.IntegerField(primary_key=True, serialize=False)),
                ('Pedidos_IdPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.pedidos')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fk_menuPedidos',
            field=models.ManyToManyField(through='restaurante.DetallePedido', to='restaurante.productos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fk_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesas'),
        ),
        migrations.CreateModel(
            name='KDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.pedidos')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.pedidos'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.productos'),
        ),
    ]
