# Generated by Django 4.2.21 on 2025-05-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_entrada_cantidad_platodefondo_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='bebestible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.bebestibles'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.entrada'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='platoDeFondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.platodefondo'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='postre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.postre'),
        ),
    ]
