# Generated by Django 4.2.21 on 2025-05-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_detallepedido_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
