# Generated by Django 4.2.21 on 2025-06-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_detallepedido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cantidad_menus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_finsemana',
            field=models.IntegerField(default=15990),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_semana',
            field=models.IntegerField(default=12990),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_total',
            field=models.IntegerField(default=0),
        ),
    ]
