# Generated by Django 4.2.21 on 2025-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_pedidos_cantidad_menus_pedidos_valor_finsemana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
