# Generated by Django 4.2.21 on 2025-06-03 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_agregadosalsa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='agregadoSalsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.agregadosalsa'),
        ),
    ]
