# Generated by Django 4.2.21 on 2025-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_detallepedido_agregadosalsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebestibles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='platodefondo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
