# Generated by Django 4.2.22 on 2025-06-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_entrada_imagen_postre_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='comentario',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
