# Generated by Django 4.2.21 on 2025-05-24 22:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('idTrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('rol', models.CharField(max_length=100)),
                ('fk_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.mesas')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('idReservas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('cantidadPersonas', models.IntegerField()),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientes')),
                ('fk_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.mesas')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('idPermisos', models.AutoField(primary_key=True, serialize=False)),
                ('fk_cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cocinero', to='users.trabajadores')),
                ('fk_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.mesas')),
                ('fk_mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_meso', to='users.trabajadores')),
                ('fk_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('rol', models.CharField(blank=True, choices=[('cocinero', 'Cocinero'), ('mesero', 'Mesero'), ('admin', 'Administrador'), ('cliente', 'Cliente')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
