# Generated by Django 4.2.21 on 2025-06-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
