# Generated by Django 5.1.7 on 2025-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_cliente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fk_restaurante',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
