-- MySQL Script generated by MySQL Workbench
-- Sat May 17 12:39:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SirveMe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SirveMe` ;

-- -----------------------------------------------------
-- Schema SirveMe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SirveMe` DEFAULT CHARACTER SET utf8 ;
USE `SirveMe` ;

-- -----------------------------------------------------
-- Table `SirveMe`.`Reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Reservas` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Apellido` VARCHAR(60) NOT NULL,
  `CantidadPersonas` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idReservas`),
  UNIQUE INDEX `idReservas_UNIQUE` (`idReservas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Clientes` (
  `FKRestaurante` INT NOT NULL AUTO_INCREMENT,
  `IDCliente` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `Comuna` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Reservas_idReservas` INT NOT NULL,
  PRIMARY KEY (`FKRestaurante`),
  UNIQUE INDEX `IDCliente_UNIQUE` (`IDCliente` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  INDEX `fk_Clientes_Reservas1_idx` (`Reservas_idReservas` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Reservas1`
    FOREIGN KEY (`Reservas_idReservas`)
    REFERENCES `SirveMe`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Proveedor` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` INT NOT NULL,
  `ValorPorPorcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInventario`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idInventario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Bebestibles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Bebestibles` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Bebestibles` (
  `idBebestible` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBebestible`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Postres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Postres` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Postres` (
  `idPostre` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPostre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`PlatosDeFondo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`PlatosDeFondo` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`PlatosDeFondo` (
  `idPlatoDeFondo` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPlatoDeFondo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Entradas` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Entradas` (
  `idEntrada` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEntrada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Pedidos` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `Mesa` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Valor` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `DetallePedido_idDetallePedido` INT NOT NULL,
  `Bebestibles_idBebestible` INT NOT NULL,
  `Postres_idPostre` INT NOT NULL,
  `PlatosDeFondo_idPlatoDeFondo` INT NOT NULL,
  `Entradas_idEntrada` INT NOT NULL,
  PRIMARY KEY (`IdPedido`),
  UNIQUE INDEX `IdPedido_UNIQUE` (`IdPedido` ASC) VISIBLE,
  UNIQUE INDEX `Fecha_UNIQUE` (`Fecha` ASC) VISIBLE,
  INDEX `fk_Pedidos_Bebestibles1_idx` (`Bebestibles_idBebestible` ASC) VISIBLE,
  INDEX `fk_Pedidos_Postres1_idx` (`Postres_idPostre` ASC) VISIBLE,
  INDEX `fk_Pedidos_PlatosDeFondo1_idx` (`PlatosDeFondo_idPlatoDeFondo` ASC) VISIBLE,
  INDEX `fk_Pedidos_Entradas1_idx` (`Entradas_idEntrada` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Bebestibles1`
    FOREIGN KEY (`Bebestibles_idBebestible`)
    REFERENCES `SirveMe`.`Bebestibles` (`idBebestible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Postres1`
    FOREIGN KEY (`Postres_idPostre`)
    REFERENCES `SirveMe`.`Postres` (`idPostre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_PlatosDeFondo1`
    FOREIGN KEY (`PlatosDeFondo_idPlatoDeFondo`)
    REFERENCES `SirveMe`.`PlatosDeFondo` (`idPlatoDeFondo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Entradas1`
    FOREIGN KEY (`Entradas_idEntrada`)
    REFERENCES `SirveMe`.`Entradas` (`idEntrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Mesas` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Mesas` (
  `idMesas` INT NOT NULL,
  `Estado` VARCHAR(20) NOT NULL,
  `Pedidos_IdPedido` INT NOT NULL,
  PRIMARY KEY (`idMesas`),
  UNIQUE INDEX `idMesas_UNIQUE` (`idMesas` ASC) VISIBLE,
  INDEX `fk_Mesas_Pedidos1_idx` (`Pedidos_IdPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Mesas_Pedidos1`
    FOREIGN KEY (`Pedidos_IdPedido`)
    REFERENCES `SirveMe`.`Pedidos` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`KDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`KDS` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`KDS` (
  `idKDS` INT NOT NULL,
  `Pedidos_IdPedido` INT NOT NULL,
  PRIMARY KEY (`idKDS`),
  INDEX `fk_KDS_Pedidos1_idx` (`Pedidos_IdPedido` ASC) VISIBLE,
  CONSTRAINT `fk_KDS_Pedidos1`
    FOREIGN KEY (`Pedidos_IdPedido`)
    REFERENCES `SirveMe`.`Pedidos` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`PedidosMesero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`PedidosMesero` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`PedidosMesero` (
  `idPedidosMesero` INT NOT NULL,
  `Pedidos_IdPedido` INT NOT NULL,
  PRIMARY KEY (`idPedidosMesero`),
  INDEX `fk_PedidosMesero_Pedidos1_idx` (`Pedidos_IdPedido` ASC) VISIBLE,
  CONSTRAINT `fk_PedidosMesero_Pedidos1`
    FOREIGN KEY (`Pedidos_IdPedido`)
    REFERENCES `SirveMe`.`Pedidos` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Administrator` (
  `idAdministrator` INT NOT NULL,
  `Inventario_idInventario` INT NOT NULL,
  PRIMARY KEY (`idAdministrator`),
  INDEX `fk_Administrator_Inventario1_idx` (`Inventario_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Administrator_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `SirveMe`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Permisos` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `Permisoscol` VARCHAR(45) NULL,
  `Permisoscol1` VARCHAR(45) NULL,
  `KDS_idKDS` INT NOT NULL,
  `PedidosMesero_idPedidosMesero` INT NOT NULL,
  `Administrator_idAdministrator` INT NOT NULL,
  PRIMARY KEY (`idPermisos`),
  INDEX `fk_Permisos_KDS1_idx` (`KDS_idKDS` ASC) VISIBLE,
  INDEX `fk_Permisos_PedidosMesero1_idx` (`PedidosMesero_idPedidosMesero` ASC) VISIBLE,
  INDEX `fk_Permisos_Administrator1_idx` (`Administrator_idAdministrator` ASC) VISIBLE,
  CONSTRAINT `fk_Permisos_KDS1`
    FOREIGN KEY (`KDS_idKDS`)
    REFERENCES `SirveMe`.`KDS` (`idKDS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_PedidosMesero1`
    FOREIGN KEY (`PedidosMesero_idPedidosMesero`)
    REFERENCES `SirveMe`.`PedidosMesero` (`idPedidosMesero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_Administrator1`
    FOREIGN KEY (`Administrator_idAdministrator`)
    REFERENCES `SirveMe`.`Administrator` (`idAdministrator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Trabajadores` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Trabajadores` (
  `idTrabajador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Permisos_idPermisos` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`, `Permisos_idPermisos`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idTrabajador` ASC) VISIBLE,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE,
  INDEX `fk_Trabajadores_Permisos1_idx` (`Permisos_idPermisos` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajadores_Permisos1`
    FOREIGN KEY (`Permisos_idPermisos`)
    REFERENCES `SirveMe`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Restaurante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Restaurante` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Restaurante` (
  `idRestaurante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Owner` VARCHAR(45) NOT NULL,
  `Mesero` VARCHAR(45) NULL,
  `Clientes_FKRestaurante` INT NOT NULL,
  `Inventario_idProducto` INT NOT NULL,
  `Mesas_idMesas` INT NOT NULL,
  `Trabajadores_idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idRestaurante`, `Clientes_FKRestaurante`, `Inventario_idProducto`, `Mesas_idMesas`, `Trabajadores_idTrabajador`),
  UNIQUE INDEX `idRestaurante_UNIQUE` (`idRestaurante` ASC) VISIBLE,
  INDEX `fk_Restaurante_Clientes_idx` (`Clientes_FKRestaurante` ASC) VISIBLE,
  INDEX `fk_Restaurante_Inventario1_idx` (`Inventario_idProducto` ASC) VISIBLE,
  INDEX `fk_Restaurante_Mesas1_idx` (`Mesas_idMesas` ASC) VISIBLE,
  INDEX `fk_Restaurante_Trabajadores1_idx` (`Trabajadores_idTrabajador` ASC) VISIBLE,
  CONSTRAINT `fk_Restaurante_Clientes`
    FOREIGN KEY (`Clientes_FKRestaurante`)
    REFERENCES `SirveMe`.`Clientes` (`FKRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurante_Inventario1`
    FOREIGN KEY (`Inventario_idProducto`)
    REFERENCES `SirveMe`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurante_Mesas1`
    FOREIGN KEY (`Mesas_idMesas`)
    REFERENCES `SirveMe`.`Mesas` (`idMesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurante_Trabajadores1`
    FOREIGN KEY (`Trabajadores_idTrabajador`)
    REFERENCES `SirveMe`.`Trabajadores` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Proveedor` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` INT NOT NULL,
  `ValorPorPorcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInventario`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idInventario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Productos` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Productos` (
  `idProductosTienda` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Agregado/Salsa` VARCHAR(45) NOT NULL,
  `TipoProducto` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`idProductosTienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SirveMe`.`Pedidos_has_ProductosTienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SirveMe`.`Pedidos_has_ProductosTienda` ;

CREATE TABLE IF NOT EXISTS `SirveMe`.`Pedidos_has_ProductosTienda` (
  `Pedidos_IdPedido` INT NOT NULL,
  `ProductosTienda_idProductosTienda` INT NOT NULL,
  PRIMARY KEY (`Pedidos_IdPedido`, `ProductosTienda_idProductosTienda`),
  INDEX `fk_Pedidos_has_ProductosTienda_ProductosTienda1_idx` (`ProductosTienda_idProductosTienda` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_ProductosTienda_Pedidos1_idx` (`Pedidos_IdPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_ProductosTienda_Pedidos1`
    FOREIGN KEY (`Pedidos_IdPedido`)
    REFERENCES `SirveMe`.`Pedidos` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_ProductosTienda_ProductosTienda1`
    FOREIGN KEY (`ProductosTienda_idProductosTienda`)
    REFERENCES `SirveMe`.`Productos` (`idProductosTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
